model_opts:
  model: BaseTransformer
  obs_input_type: [box, speed, pose]
  apply_class_weights: True
  normalize_boxes: True
  generator: False
  reshape_input_to_1d_list: True
  process_input_features: 
    enabled: True
    indexes_to_stack: [0,1,2]
    static_features_indexes: []
    super_resolution: False
  pose_configs:
    keep_most_stable_keypoints: True
    add_distances_between_keypoints: True
    add_angles_between_limb_and_axis: False
    add_joints_angles: False
    add_joints_angles_diff: False
  input_embedding:
    active: False
  positional_encoding:
    active: False
net_opts:
  num_hidden_units: 128
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg16
exp_opts:
  datasets: [jaad_all]
  batch_size: [32, 32, 32]
  epochs: [100, 50, 50]
  lr: [0.00001, 0.00001, 0.00001]
