model_opts:
  model: MultiBranchGraphTFV6
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_context_with_segmentation_v0, scene_context_with_segmentation_v5,
                   scene_graph, scene_graph_doubled,
                   scene_context, scene_context_doubled,
                   scene_context_non_static, scene_context_with_segmentation_v3, 
                   box, speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features: 
    enabled: True
    indexes_to_stack: [8,9]
    static_features_indexes: []
  vanilla_transformer:
    normalize_boxes: True
    pose_configs:
      keep_most_stable_keypoints: True
      add_distances_between_keypoints: False
      add_angles_between_limb_and_axis: False
      add_joints_angles: False
      add_joints_angles_diff: False
    input_embedding:
      active: False
    positional_encoding:
      active: False
    net_opts:
      num_hidden_units: 128
      global_pooling: avg
      regularizer_val: 0.0001
      cell_type: gru
      backbone: vgg16
exp_opts:
  datasets: [jaad_beh]
  batch_size: [32, 4, 4]
  epochs: [5, 40, 40]
  lr: [5.0e-05, 5.0e-06, 5.0e-06]
