model_opts:
  model: SmallTrajectoryTransformerb
  apply_class_weights: True
  generator: True
  obs_input_type: [box, speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features: 
    enabled: True
    indexes_to_stack: [0,1]
    static_features_indexes: []
  normalize_boxes: True
exp_opts:
  datasets: [pie]
  batch_size: [16]
  epochs: [60]
  lr: [5.0e-06]
