model_opts:
  model: SmallTrajFusionNet
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_context_with_ped_overlays_combined,
                   box, veh_speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features: 
    enabled: True
    indexes_to_stack: [1,2]
    static_features_indexes: []
exp_opts:
  datasets: [pie]
  batch_size: [16]
  epochs: [60]
  lr: [5.0e-06]
