model_opts:
  model: Static
  obs_input_type: [local_context]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  backbone: vgg16
exp_opts:
  datasets: [jaad_all]
  batch_size: [32, 32, 32]
  epochs: [20, 10, 5]
  lr: [0.000001, 0.000001, 0.000001]
