model_opts:
  model: TrajFusionNet
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_context_with_ped_overlays, 
                   scene_context_with_ped_overlays_previous,
                   box, veh_speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: [2, 3]
    static_features_indexes: []
exp_opts:
  datasets: [jaad_beh]
  batch_size: [16]
  epochs: [1]
  lr: [5.0e-06]
