model_opts:
  model: TrajectoryTransformer
  apply_class_weights: True
  generator: True
  obs_input_type: [box, speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: [0, 1]
    static_features_indexes: []
exp_opts:
  datasets: [jaad_beh]
  batch_size: [64]
  epochs: [40]
  lr: [5.0e-05]
