model_opts:
  model: VAN
  obs_input_type: [scene_context_with_ped_overlays]
  apply_class_weights: True
  generator: True
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features: 
    enabled: True
    static_features_indexes: [0]
exp_opts:
  datasets: [jaad_all]
  batch_size: [16, 4, 4]
  epochs: [15, 6, 6]
  lr: [5.0e-05, 5.0e-05, 5.0e-05]
