model_opts:
  model: VisionTransformer
  obs_input_type: [scene_context_with_segmentation_v3]
  apply_class_weights: True
  generator: True
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features: 
    enabled: True
    static_features_indexes: [0]
exp_opts:
  datasets: [pie]
  batch_size: [16, 4, 4]
  epochs: [5, 6, 6]
  lr: [5.0e-06, 5.0e-06, 5.0e-06]
